---
  - name: Handlers
    hosts: Devnode
    gather_facts: true
    become: yes
    tasks:
       - name: using Handlers
         ping:
         notify: call
      
    handlers:
       - name: call
         ansible.builtin.service:
            name: httpd
            state: started
      
    
         