---
- name: Ping Linux hosts
  hosts: Devnode
  become: true
  become_user: root
  gather_facts: yes
  tasks:
    - name: Ping
      ping:
      register: op
    - name: Extracts the ping key from the registered output variable
      debug:
        msg: "{{ op.ping }}"
    - name: hostname of manged node
      debug:
        msg: "{{ ansible_hostname }}"
