---
- name: Ping Linux hosts
  hosts: Devnode
  become: false
  gather_facts: true
  tasks:
    - name: Ping
      ping:

    - name: check sshd service status
      service:
        name: sshd
        state: started
      register: output
    
    - name: displaying status of sshd service
      debug:
       msg: "{{ output }}"